### ISSUE TITLE
Helmet values

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#1]
- [x] I need a meta description:

something like...

"Carbon is the design system for IBM web and product. It is a series of individual styles, components, and guidelines used for creating unified UI."

- [x] I need meta keywords:

something like...

"IBM, design, system, Carbon, design system, Bluemix, styleguide, style, guide, components, library, pattern, kit, component, cloud"

**Comment by eleanorbartosh** [comment]
Meta Description:
IBM Design Research helps teams uncover insights and inform the experiences we create for people. It is at the heart of Enterprise Design thinking,

Meta Keywords:
IBM, design, research, design research, design thinking, human-centered design, interviewing, user research, interviews, user experience research, service design, ux research, design strategy, people, practice, observation, user interviews, anthropology

for a favicon, please ask Cris Gonzalez when he's back from vacation
