### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#101]
should it not have this content?

<img width="397" alt="Screen Shot 2019-08-09 at 2 51 55 AM" src="https://user-images.githubusercontent.com/32881239/62742650-64344880-ba0d-11e9-92dd-d0e59f4348e7.png">

**Comment by sstrubberg** [comment]
@air2h2o I recall you guys wanting to scrap this.

**Comment by mjabbink** [comment]
you don’t want to offer people emailing you for feedback or create an issue on GitHub?

**Comment by eleanorbartosh** [comment]
We don't have an email address we actively monitor. We could point them towards our IBM Design Twitter, perhaps, which IS actively monitored? @mjabbink @sstrubberg @air2h2o

**Comment by eleanorbartosh** [comment]
"Have questions or comments, tag us on Twitter." or something like that.

**Comment by air2h2o** [comment]
This is what we say in the body copy of SUP overview: 

Questions or comments? Start a conversation with us on Twitter at @IBMDesign #designresearch. If you’re an IBM employee, you can join the conversation on our internal IBM Studios Slack on #ibm-design-research.
