### ISSUE TITLE
ethics vs. code of conduct

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#13]
https://idr-public.netlify.com/ethics

Q: Is Ethics the word we want to use, or should we say “Code of Conduct” which is what the text page says

A: Should be Ethics (on the side bar navigation. Header on page should be "Design research ethics" to mirror the structure on the AI Design pages. 

lame mock-up... but you get the idea. 

<img width="697" alt="Screen Shot 2019-07-03 at 11 12 37" src="https://user-images.githubusercontent.com/26859234/60607761-8a6a2700-9d83-11e9-8489-7acf3049ea70.png">

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/60610558-affa2f00-9d89-11e9-9dc8-669064217d10.png)

fixed
