### ISSUE TITLE
side bar navigation... "IBM Internal Resources" broken link

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#134]
On the side bar navigation, the IBM Internal Resources link is broken. 

http://idr-prod.w3ibm.mybluemix.net/design/research/resources/

also when I go to w3.ibm.com/design/research... it is the old and external version of the site without all the internal resources. Is it possible to move idr-prod to w3 or at least redirect?

**Comment by kellychurchill** [comment]
Thanks @air2h2o We are aware of this issue and @sstrubberg should be pushing a fix soon

**Comment by sstrubberg** [comment]
I'm just going to bring all of the internal resources into our new w3 design build.
