### ISSUE TITLE
Remove space after “We are not our users” on home page

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#135]
![C5D627D1-F05B-47D4-93B7-2C239643EBF3](https://user-images.githubusercontent.com/32881239/64065186-558a1d00-cbd8-11e9-8ea9-3d1b8f496af2.jpeg)

Check out IDL, Design for AI and Carbon home pages.

**Comment by mjabbink** [comment]
Status?

**Comment by mjabbink** [comment]
Also I think  “Design research” should update to “Design Research”

**Comment by mjabbink** [comment]
There is still a full return under "We are not our users". This makes it look like a header and there is a header to the left (Our practice). It should likely be removed. Too much messaging.

This should likely read like...

Our practice

Design research guides teams to uncover insights and inform the experiences we create. It begins with the rigorous study of the people we serve and their context. This is the heart of Enterprise Design Thinking. While in the Loop, design research leads teams to continuously build understanding and empathy through observation, prototyping possible solutions, and reflecting on the feedback from our users themselves.


or


We are not our users. Design research guides teams to uncover insights and inform the experiences we create. It begins with the rigorous study of the people we serve and their context. This is the heart of Enterprise Design Thinking. While in the Loop, design research leads teams to continuously build understanding and empathy through observation, prototyping possible solutions, and reflecting on the feedback from our users themselves.

The first one reads better. "We are not our users" can live within the content somewhere else.

**Comment by mjabbink** [comment]
<img width="1169" alt="Screen Shot 2019-10-16 at 1 25 30 PM" src="https://user-images.githubusercontent.com/32881239/66947415-7687bf80-f018-11e9-9f30-4a138afb265b.png">

**Comment by sstrubberg** [comment]
Do a
