### ISSUE TITLE
Home page: Reduce line weight of underline in intro text.

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#137]
@RyanCaruthers and Jeannie Servaas/Shixie can spec but I think already done.

@alisonjoseph Carbon component issue but needs to be resolved since this is lingering too long.

<img width="778" alt="Screen Shot 2019-09-04 at 7 39 05 PM" src="https://user-images.githubusercontent.com/32881239/64300923-c02ab800-cf4c-11e9-9755-9b54409d21b1.png">

**Comment by alisonjoseph** [comment]
I can get this updated in the theme for this large text. this is with a border-bottom of 1px. Is there a spec somewhere so I can get the distance correct?

<img width="698" alt="Screen Shot 2019-09-04 at 9 09 27 PM" src="https://user-images.githubusercontent.com/2753488/64306450-6334ff00-cf58-11e9-9daa-45256c059dcd.png">

**Comment by mjabbink** [comment]
Jeannie can provide spec. It’s a bit far away in your sketch

**Comment by shixiedesign** [comment]
A bit of context: we changed spec from `border` to `text-decoration` because it required the link component to automatically display as `block`. If we want to use `border` in Gatsby theme, it's easy but we cannot change the Carbon component's link because of the change in behavior. See issue https://github.com/carbon-design-system/carbon/issues/3059 where this is discussed.

**Comment by vpicone** [comment]
One advantage of using text decoration is that you get nice styling around the descender.

![Screen Shot 2019-09-24 at 2 59 29 PM](https://user-images.githubusercontent.com/4078018/65545895-f15b3000-dedb-11e9-9270-d5691e794ea7.png)

[`text-decoration-thickness`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-thickness) is coming (but only supported by firefox and safari at the moment).

**Comment by mjabbink** [comment]
that is a must. It cannot go under the descender.

**Comment by mjabbink** [comment]
@vpicone still an issue here. Did we resolve in Gatsby theme? The line is too think here

**Comment by mjabbink** [comment]
We should include Jeannie to help sort out the spec.

**Comment by mjabbink** [comment]
@jeanservaas

**Comment by vpicone** [comment]
@mjabbink Controlling the thickness of link underlines isn't yet possible in [every browser](https://caniuse.com/#feat=mdn-css_properties_text-decoration-thickness). We can add the property and browsers that recognize it will use it, however Chrome and Edge don't yet support it.

I'm going to move this issue to Carbon and open a PR to add the rule. It's a matter of when, not if Chrome and Edge add support, once they do it'll 'just work' so I feel comfortable adding it now.

**Comment by mjabbink** [comment]
@vpicone ok, this one is mega low priority compared to the other stuff we have cooking. I’m totally fine as is until the time comes.

**Comment by vpicone** [comment]
Opened https://github.com/IBM/plex/issues/293 to make sure the thickness is intentional before trying to solve this with css.

**Comment by sstrubberg** [comment]
Is this still an issue on does the conversation on the Plex repo resolve it?

**Comment by alisonjoseph** [comment]
this appears resolved.
