### ISSUE TITLE
Landing page copy

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#14]
Phil's re-write is nice and pithy. @eleanorbartosh and I made a few tweaks. 

copy should be: 

Our Practice (header)

Design research helps teams uncover insights to inform the experiences we create. It begins with the rigorous study of the people we serve and the ecosystems in which they exist. This is the heart of Enterprise Design Thinking. While in the Loop, design research leads teams to continuously build understanding and empathy through observation, prototyping possible solutions, and reflecting on the feedback from our users themselves. 
Learn more about the business impact of Design Research and Enterprise Design Thinking in this Forrester report."

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/60609808-25fd9680-9d88-11e9-821b-fa9c02f9499c.png)

 got it.
