### ISSUE TITLE
Landing Page---SVG Circles Aliasing

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#14]
![image](https://user-images.githubusercontent.com/15822070/57082247-f7960900-6cbb-11e9-8223-3a1e3a22d4fe.png)

- [ ] 1. Line weight of the circles is too small, the tops and bottoms are fading out

- [x] 4. reduce padding by 1/3 or so.

**Comment by sstrubberg** [comment]
@crisgonz90 i need help with 1.

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/57089918-31bad700-6ccb-11e9-8e7f-23e1326b96c5.png)

I dropped the height from 560px to 500px. Thoughts?

@air2h2o

**Comment by air2h2o** [comment]
@crisgonz90 is a 'heart' icon too obvious?
