### ISSUE TITLE
home page content is way too complicated

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#140]
A biggie for me. This text can be so streamlined and way more impactful, meaningful, clear, and simple with half the amount of content. be essential. Say what you need(and one or two ideas not the 7 or 8.  Be confident and clear and reduced. You can’t say it all up in this lead space. If it’s important to say fold in elsewhere in a logical place. All of this cannot be said in these three chunks of text and all up top. There is no argument for this.

<img width="1179" alt="Screen Shot 2019-09-25 at 10 28 14 PM" src="https://user-images.githubusercontent.com/32881239/65656127-57cb7580-dfe4-11e9-940a-48592ff96dfa.png">

**Comment by air2h2o** [comment]
@mjabbink Eleanor is traveling the rest of the week. When she is back next week, we'll take a look see how to parse it down. Product pages (non-/design) that you feel like are stellar examples for our reference?

**Comment by mjabbink** [comment]
@sstrubberg I must be getting real old because I created this issue in the wrong repo! It’s totally meant for the IoT site. Please disregard this and I’ll recreate in correct repo.
