### ISSUE TITLE
Links that require logging in

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#17]
The 5 Why's Link on this page requires login. Do we have a POV on requiring that? 

<img width="1429" alt="Screen Shot 2019-07-03 at 10 16 03" src="https://user-images.githubusercontent.com/26859234/60609033-5f350700-9d86-11e9-8128-14cfd165cb3a.png">

I love linking to help people do it themselves, but am concerned about the speed bump that may provide to our readers.

**Comment by eleanorbartosh** [comment]
@sstrubberg I know you updated the tiny text above 5 Whys. Can you please also add this sentence to the end of the paragraph: 

You can practice this skill with our Enterprise Design Thinking activity, "5 Whys":

Then the 5 whys box should read:
(tiny text) Account registration required
(normal text) Try the 5 Whys activity today

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61064508-8794b500-a3c7-11e9-935d-21d503748f50.png)

**Comment by eleanorbartosh** [comment]
@air2h2o I am still "meh" on this. What do you think?
