### ISSUE TITLE
Find the story link (second link)

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#19]
Please link "You can read IBM's guidance on data visualization [here](https://www.ibm.com/design/v1/language/experience/data-visualization/)." accordingly

**Comment by sstrubberg** [comment]
there is no txt "data visualization" in the Find the story section.

**Comment by eleanorbartosh** [comment]
It should be in the pull request. No? Bleh. If not, the new sentence and link should go at the end of small paragraph that follows "Enhance meaning with visuals"

**Comment by sstrubberg** [comment]
ohhhhhh! gotcha. i see it in the PR.

You know.. you can make that change if you want to...

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links
