### ISSUE TITLE
Ethics page: The body text goes beyond the column width

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#22]
https://idr-public.netlify.com/ethics

![Screen Shot 2019-07-03 at 1 38 38 PM](https://user-images.githubusercontent.com/32881239/60612948-e343ba80-9d97-11e9-87e6-ca3e6ae3f765.png)

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/60619036-5865be80-9d9d-11e9-9499-75e71234bcb9.png)

Fixed with latest version of Gatsby-theme.
