### ISSUE TITLE
Indentation on lists

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#26]
![image](https://user-images.githubusercontent.com/15822070/60843598-c0047b00-a19c-11e9-900a-aeefdb57a8a4.png)

**Comment by eleanorbartosh** [comment]
I also noticed this issue at the bottom of this page as part of the "Where You Come In" Guide and Explorer lists:
<img width="658" alt="Screen Shot 2019-07-08 at 4 37 26 PM" src="https://user-images.githubusercontent.com/49251920/60844374-afed9b00-a19e-11e9-80a9-ddff7a793801.png">
 https://idr-public.netlify.com/sponsor-user-program/overview

**Comment by sstrubberg** [comment]
waiting on Gatsby-Theme update

**Comment by eleanorbartosh** [comment]
Do you know if this is coming soon? Or totally TBD?

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61066675-98472a00-a3cb-11e9-9f16-b55115cf1cf9.png)

i fixed it

**Comment by eleanorbartosh** [comment]
👏 cool, thanks. once you push this + the accordion, @air2h2o and I will do a solid content review on the SU pages.

**Comment by eleanorbartosh** [comment]
@sstrubberg im good with this for now
