### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#27]
Hi Scott, a few updates for the IDR homepage: 

1
Can you please link "Enterprise Design Thinking" in the opening copy? Link: https://ibm.com/design/thinking
<img width="1084" alt="Screen Shot 2019-07-08 at 4 24 00 PM" src="https://user-images.githubusercontent.com/49251920/60843624-d4487800-a19c-11e9-98d9-0d4431e283e9.png">

2
Please remove "Learn more about the business impact of Design Research and Enterprise Design Thinking in this Forrester report."

3
Can you please capitalize "Sponsor User Program" in the homepage box? Also please update the blurb to be: "Design for real users rather than assumed needs" (it's currently a copy of the "research in practice" box.) Also please update the box linking URL to: https://idr-public.netlify.com/sponsor-user-program/overview

<img width="464" alt="Screen Shot 2019-07-08 at 4 25 17 PM" src="https://user-images.githubusercontent.com/49251920/60843817-4e78fc80-a19d-11e9-893b-83f08eb28cdf.png">

(@air2h2o -- we can talk about whether SUP should be on the homepage)

4
Please cut the "Why we do it" section in white near bottom

5
Please remove the middle medium post "Fun and Accuracy" and replace it with a link + graphic to go to the Forrester Report (previously linked above in # 2) - Cris G might be able to support with graphics.

**Comment by sstrubberg** [comment]
1. ✅ 
2. ✅ 
3. ✅ 
4. ✅ 
5. ✅ 

![image](https://user-images.githubusercontent.com/15822070/60916995-82175d80-a255-11e9-8313-3a1a5c39a473.png)

**Comment by eleanorbartosh** [comment]
@sstrubberg We should use a different graphic for the new Forrester tile. Cris G. may have some feedback. It could be a stylized statistic similar to what we use on the EDT homepage or in our presentations.
