### ISSUE TITLE
Gather docs and links for Scott

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#29]
@air2h2o we have to gather documents and links for Scott. This is an issue to capture that and remind us. Maybe we can document them all here? @sstrubberg do you have a preference for a delivery mechanism?

**Comment by air2h2o** [comment]
Off the top of my head, definitely need to update the 

1. Research Plan & 
2. Protocol (should probably also articulate the difference)

**Comment by sstrubberg** [comment]
Research as a team ->
![image](https://user-images.githubusercontent.com/15822070/60918386-cf48fe80-a258-11e9-8e81-8cc04cc4fb4b.png)
