### ISSUE TITLE
Accordion functionality for SU FAQ?

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#30]
Is it possible to use an accordion functionality or similar to hide/reveal the FAQ and answers? Example: https://idr-public.netlify.com/sponsor-user-program/starting

<img width="749" alt="Screen Shot 2019-07-08 at 4 39 21 PM" src="https://user-images.githubusercontent.com/49251920/60844461-f5aa6380-a19e-11e9-95e5-20c9394efbb8.png">

**Comment by sstrubberg** [comment]
The GatsbyTheme doesn't have accordion functionality yet.

**Comment by sstrubberg** [comment]
they JUST release an accordion!

**Comment by eleanorbartosh** [comment]
woooooooooo

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61066549-65049b00-a3cb-11e9-976d-322ea3141bd5.png)

**Comment by eleanorbartosh** [comment]
That's really nice! Questions:

- How do you feel about the extra padding on the left? Do we need it? Does that match AI? (etc). 
- Can you please add a little padding on the right between the text and down arrow. In the second from the bottom Q, you can see "whom" gets too close to the arrow.
- Is that arrow facing the right way? I always get confused about when it should be like that vs. sideways.
- What does an expanded state look like?
