### ISSUE TITLE
Landing Page --- Bump h4's to h3's.

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#31]
![image](https://user-images.githubusercontent.com/15822070/57538284-b5994280-730d-11e9-90a5-214a2db41491.png)

![image](https://user-images.githubusercontent.com/15822070/57538297-bb8f2380-730d-11e9-9d3d-bccdf5f8c361.png)

![image](https://user-images.githubusercontent.com/15822070/57538304-bf22aa80-730d-11e9-8a9a-f45019ba0a7d.png)

![image](https://user-images.githubusercontent.com/15822070/57538315-c47ff500-730d-11e9-8d7c-b5fa4cbc0a32.png)

**Comment by air2h2o** [comment]
👍
