### ISSUE TITLE
Updates to social links in the footer

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#31]
- [ ] Social links don't open in a new tab. Should they?
- [x] Please move medium from the left sidebar to the footer
- [x] It is TBD whether we'll update Facebook (I've checked with Will). If not, I suggest cutting. Will confirm in next couple days.
- [x] update contact email (@air2h2o do we want to do this....)

**Comment by air2h2o** [comment]
- [ ] Ryan's idea of mimicking the external links for W3 was a nice pattern, and therefore including all the main categories of resources: Training Modules, Software, External Vendors, Transcriptions, etc.

**Comment by sstrubberg** [comment]
Medium is moved.
I removed the contact email entirely until hear otherwise from ya'll.
Social links don't open a new tab --- i made an issue with the Gatsby-Theme crew. AI doesn't have this either.
I'll cut FB based on your input from Will.

**Comment by eleanorbartosh** [comment]
@sstrubberg remove Facebook please! confirmed w/ Will

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61064882-3933e600-a3c8-11e9-936f-76711d84e870.png)

**Comment by eleanorbartosh** [comment]
approved, thanks!
