### ISSUE TITLE
Update sidebar "W3 Design Research" link

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#32]
- [x] Remove medium and move down to footer (referenced in #31)
- [ ] Using a similar style to the righthand menu (see screenshot below), update the lefthand nav's "W3 Design Research" text to be:

IBM Internal Resources**
(line)
- Training Modules
- Agreements
- Software
- Recruitment and Services
(this refers to the content that's linked to from here: http://idr-prod.w3ibm.mybluemix.net/design/research/resources/ but I guess those pages will change??)

**If "IBM Design Research Internal Resources" fits on one line or looks good on two, can we do that instead?

<img width="308" alt="Screen Shot 2019-07-08 at 4 44 08 PM" src="https://user-images.githubusercontent.com/49251920/60844811-12936680-a1a0-11e9-9177-962256f3bb10.png">

**Comment by sstrubberg** [comment]
`IBM Design Research Internal Resources` doesn't fit 😢 

How do you imagine the linking working if we list out the internal sections? This feels like we're over-complicating what was supposed to an easy link back to W3. I vote we keep it as-is.

**Comment by eleanorbartosh** [comment]
@sstrubberg Can we use "IBM Internal Resources" then? (Does that fit?) As for linking for internal sections... are we not building those pages in the new style anyway? What would the links be as you were currently imagining?

**Comment by sstrubberg** [comment]
![image](https://user-images.githubusercontent.com/15822070/61064696-e3f7d480-a3c7-11e9-8fd2-6739849ef688.png)

I need more clarity for your 2nd and 3rd question :)

**Comment by eleanorbartosh** [comment]
Link approved! We can talk more about Q2 and 3!
