### ISSUE TITLE
Landing Page --- Copy Layout

### ISSUE THREAD

**Issue by sstrubberg** [IBM-Design/idr#32]
move body copy to the right, headers remain on left

old layout
![image](https://user-images.githubusercontent.com/15822070/57539040-399ffa00-730f-11e9-8ea1-3fe2a896965d.png)

new layout
![image](https://user-images.githubusercontent.com/15822070/57539066-46bce900-730f-11e9-9da8-d5048c8cad1b.png)

**Comment by air2h2o** [comment]
👍
