### ISSUE TITLE
Research as a team, bullet on mobile

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#52]
on mobile (iOS 12, safari browser) the bullets second line indent is off. See attached. 

![IMG_1637](https://user-images.githubusercontent.com/26859234/61340368-a2bc5600-a807-11e9-894d-039730068719.PNG)

**Comment by sstrubberg** [comment]
This is a gatsby theme issue. Cross-posting.

**Comment by sstrubberg** [comment]
hide the icon at small screen widths.

**Comment by eleanorbartosh** [comment]
did this get fixed?

**Comment by alisonjoseph** [comment]
This was fixed
