### ISSUE TITLE
footer too short. See Gatsby footer and height

### ISSUE THREAD

**Issue by mjabbink** [IBM-Design/idr#53]

**Comment by sstrubberg** [comment]
@vpicone @alisonjoseph Can you comment on this? I'm not doing any thing special with the Footer except alter the copy.

**Comment by alisonjoseph** [comment]
I have an issue open on the theme repo already around the footer, I think there might be some design fixes we need. I'll try and track down the original spec https://github.com/carbon-design-system/gatsby-theme-carbon/issues/200
