### ISSUE TITLE
Sponsor User Program overview page

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#69]
The cards on the Overview page do not require a description - https://idr-public.netlify.com/sponsor-user-program/overview

<img width="905" alt="Screen Shot 2019-07-24 at 1 56 38 PM" src="https://user-images.githubusercontent.com/49251920/61820603-ecfe9200-ae1a-11e9-9d5f-f7fae15eca44.png">

An alternative to this would be to scrap the cards altogether and use the arrow + link UX pattern. I'm not sure, though, if that is only used to drop you down the page?

**Comment by sstrubberg** [comment]
I'm down for whatever. Let's check with Ryan.

**Comment by eleanorbartosh** [comment]
Also slacked to Ryan again.

**Comment by alisonjoseph** [comment]
Closing out old issues, please re-open with info if still needed.
