### ISSUE TITLE
Update the SUP overview deck in new viz lang

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#72]
Then link to it on the Sponsor User Program "Starting" page, under pro-tip # 1. We might also create an external specific version and link to it in Learn More section at very bottom - 

Original text:
"When recruiting Sponsor Users, provide clients program details and requirements to gauge their interest and availability. IBM Design created template presentations to help educate your team and pitch the program to a potential Sponsor User. You can download them in the “Learn more” box below."

**Comment by alisonjoseph** [comment]
Closing old issues, please re-open if still needed.
