### ISSUE TITLE
Bullets vs. Numbers on Sponsor User Pages

### ISSUE THREAD

**Issue by eleanorbartosh** [IBM-Design/idr#74]
On our SU Program pages, we use a mix of bullets (for suggested steps) and numbers (for pro-tips). This differentiation in styling is a hold over from the original site. While reviewing today, we began to question this. Why are they different? Should they be the same? Do bullets vs. numbers mean something intentional? How are we handling this on other pages? @CrisGonzo, @Mike, @Ryan? 

https://idr-public.netlify.com/sponsor-user-program/planning

**Comment by CrisGonzo** [comment]
could we try doing this 
![image](https://user-images.githubusercontent.com/16339298/61891803-20e7bf00-aed0-11e9-8a14-71f500a17429.png)

can be seen on https://www.ibm.com/design/ai/ethics/fairness

**Comment by eleanorbartosh** [comment]
could be interesting for the pro-tips, but I think there are generally too many of the suggested steps.

**Comment by sstrubberg** [comment]
close?
