### ISSUE TITLE
hero / swap tiles overlaid on video

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#84]
- [x] replace video tile remove "Ethics & responsibility" tile replace with "Research in practice"

- [ ] Can we overlay "We are not our users" over the video? 

- [x] body copy: new sentence: It begins with the rigorous study of the people we serve and their context. (instead of the ecosystem in which they exist)

**Comment by sstrubberg** [comment]
@air2h2o Check with Ryan on bullet 2

**Comment by eleanorbartosh** [comment]
I slacked Ryan

**Comment by RyanCaruthers** [comment]
@eleanorbartosh @air2h2o The current Gatsby theme we are moving over to doesn't currently have a pattern that uses large type or phrase at the top over the video areas. No responsive options right now.

Currently how it is laid out is supporting the consistency of other practices sites. Not to say we can't explore it in the future when we have more time while continuing to address the rest of the pages with more visual support and so on.
