### ISSUE TITLE
double check type scale consistency

### ISSUE THREAD

**Issue by air2h2o** [IBM-Design/idr#92]
![Screen Shot 2019-08-01 at 16 56 09](https://user-images.githubusercontent.com/26859234/62330108-4b5fec00-b47d-11e9-8468-219c9c6ff2bf.png)

Need to check type scale. these different pages should match but currently one is bigger than the other.

**Comment by sstrubberg** [comment]
I'm having a hard time re-creating this... Can you stop by sometime and show me?

**Comment by air2h2o** [comment]
yes, definitely, may need to be tomorrow.

**Comment by eleanorbartosh** [comment]
I was just able to replicate it. It's not the title of the page, it's the subhead H tags. The larger issue is that they need to be consistent across the site. In this case, the subhead styles on https://idr-public.netlify.com/guiding-principles/stay-curious and https://idr-public.netlify.com/research-in-practice/craft-insights are correct and match the AI site. Any other smaller H tags throughout the site should match these.
